language: java
jdk:
  - openjdk10
before_install:
  - sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/mill/releases/download/0.2.6/0.2.6) > ~/mill && chmod +x ~/mill'
install:
  - ~/mill dotenv.publishLocal
script:
  - ~/mill dotenv.tests
  - (cd example; ~/mill hello.run)
  - (cd example; ~/mill hello.tests)

